name: student
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  adaptive_dialog: ^1.6.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.1.1
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.0.2
  get: ^4.6.1
  get_it: ^7.2.0
  http: ^0.13.4
  json_serializable: ^6.1.6
  localization: ^2.1.0
  provider: ^6.0.2
  random_string: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.10

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
